-- Criação de tabela empresa_filial
-- Davi Queiroz

IF NOT EXISTS(SELECT * FROM SYS.TABLES WHERE name = 'empresa_filial')
CREATE TABLE empresa_filial (
	id bigint PRIMARY KEY NOT NULL  IDENTITY(1,1),
	sigla VARCHAR(255),
	nome_filial VARCHAR(255) NOT NULL,
	subordinacao_empresa VARCHAR(255) NOT NULL,
	empresa_matriz BIT,
	tipo_filial VARCHAR(255) NOT NULL,
	cnae_id BIGINT NOT NULL,
	codigo_pagamento_gps_id BIGINT NOT NULL,
	situacao VARCHAR(255) NOT NULL,
	esfera_orgao VARCHAR(255) NOT NULL,
	qtd_proprietario INT,
	tipo_estabelecimento VARCHAR(255) NOT NULL,
	capital_social_anual FLOAT NOT NULL,
	dt_inicial_atividade DATETIME2(7),
	referencia_contribuicao VARCHAR(255) NOT NULL,
	atividade_primaria VARCHAR(255) NOT NULL,
	natureza_estabelecimento VARCHAR(255) NOT NULL,
	banco_id BIGINT NOT NULL,
	agencia INT NOT NULL,
	fpas INT NOT NULL,
	conta_fgts INT,
	cd_gpras_acidente_trabalho INT,
	cnpj_cei VARCHAR(255) NOT NULL,
	inscricao_anterior INT,
	codigo_empregador INT,
	rais_negativa INT NOT NULL,
	percentual_empregador FLOAT,
	sat FLOAT NOT NULL,
	salario_educacao FLOAT NOT NULL,
	senai FLOAT NOT NULL,
	sesi FLOAT NOT NULL,
	senac FLOAT NOT NULL,
	sesc FLOAT NOT NULL,
	sebrae FLOAT NOT NULL,
	senar FLOAT NOT NULL,
	senat FLOAT NOT NULL,
	set_col FLOAT NOT NULL,
	secoop FLOAT NOT NULL,
	dpc FLOAT NOT NULL,
	forca_aerea FLOAT NOT NULL,
	cd_acidente_trabalho INT NOT NULL,
	logradouro VARCHAR(255),
	numero VARCHAR(255),
	complemento VARCHAR(255),
	cep VARCHAR(255),
	uf_id BIGINT,
	bairro VARCHAR(255),
	municipio_id BIGINT,
	telefone VARCHAR(255),
	anexo_id BIGINT,
	tipo_inscricao VARCHAR(255) NOT NULL,
	created_at datetime2(7) NOT NULL,
	updated_at datetime2(7) NOT NULL,
	created_by bigint,
	updated_by bigint,
	CONSTRAINT fk_cnae_id FOREIGN KEY (cnae_id) REFERENCES cnae(id),
	CONSTRAINT fk_codigo_pagamento_gps_id FOREIGN KEY (codigo_pagamento_gps_id) REFERENCES codigo_pagamento_gps(id),
	CONSTRAINT fk_banco_id FOREIGN KEY (banco_id) REFERENCES banco(id),
	CONSTRAINT fk_uf_id FOREIGN KEY (uf_id) REFERENCES unidade_federativa(id),
	CONSTRAINT fk_municipio_id FOREIGN KEY (municipio_id) REFERENCES municipio(id),
	CONSTRAINT fk_anexo_id FOREIGN KEY (anexo_id) REFERENCES anexo(id)
)