--Criação da tabela correcao.
--Davi Queiroz

IF NOT EXISTS(SELECT * FROM SYS.TABLES WHERE name = 'correcao')
CREATE TABLE correcao (
	id bigint NOT NULL IDENTITY(1,1),
	dt_competencia datetime2(7) NOT NULL,
	tipo_processamento_id bigint NOT NULL,
	empresa_id bigint,
	filial_id bigint,
	lotacao_id bigint,
	centro_custo_id bigint,
	sindicato_id bigint,
	funcao_id bigint,
	nivel_salarial_id bigint,
	situacao_afastamento_id bigint,
	tipo_folha_id bigint,
	verba_id bigint,
	valor_faixa_I numeric(13,3),
	valor_faixa_II numeric(13,3),
	percentual_produto float,
	percentual_aumento float,
	valor_produto numeric(13,3),
	valor_piso numeric(13,3),
	tipo_arredondamento int,
	avos int,
	valor_arrendamento numeric(13,3),
	atualiza_mes int,
	retroativo datetime2(7),
	abono bit,
	verba_abono int,
	created_at datetime2(7) NOT NULL,
	updated_at datetime2(7) NOT NULL,
	created_by bigint,
	updated_by bigint,
	CONSTRAINT pk_correcao PRIMARY KEY (id),
	CONSTRAINT fk_correcao_tipo_processamento_id FOREIGN KEY (tipo_processamento_id) REFERENCES tipo_processamento(id),
	CONSTRAINT fk_correcao_empresa_id FOREIGN KEY (empresa_id) REFERENCES empresa_filial(id),
	CONSTRAINT fk_correcao_filial_id FOREIGN KEY (filial_id) REFERENCES empresa_filial(id),
	CONSTRAINT fk_correcao_centro_custo_id FOREIGN KEY (centro_custo_id) REFERENCES centro_custo(id),
	CONSTRAINT fk_correcao_sindicato_id FOREIGN KEY (sindicato_id) REFERENCES sindicato(id),
	CONSTRAINT fk_correcao_funcao_id FOREIGN KEY (funcao_id) REFERENCES funcao(id),
	CONSTRAINT fk_correcao_nivel_salarial_id FOREIGN KEY (nivel_salarial_id) REFERENCES nivel_salarial(id),
	CONSTRAINT fk_correcao_situacao_afastamento_id FOREIGN KEY (situacao_afastamento_id) REFERENCES afastamento(id),
	CONSTRAINT fk_correcao_tipo_folha_id FOREIGN KEY (tipo_folha_id) REFERENCES tipo_folha(id),
	CONSTRAINT fk_correcao_verba_id FOREIGN KEY (verba_id) REFERENCES verba(id)
)