--Lucas Moura
--Adicionando coluna nova na tabela de menu.

UPDATE menu set url = '/usuario/gestao' where nome = 'Usuários';
UPDATE menu set url = '/areaFormacao/gestao' where nome = 'Área de Formação';
UPDATE menu set url = '/atividade/gestao' where nome = 'Atividade';
UPDATE menu set url = '/banco/gestao' where nome = 'Bancos';
UPDATE menu set url = '/categoriaDoenca/gestao' where nome = 'Categorias de Doenças';
UPDATE menu set url = '/subCategoriaDoenca/gestao' where nome = 'Subcategorias de Doenças';
UPDATE menu set url = '/classificacaoInternacionalDoenca/gestao' where nome = 'Classificação de Doenças';
UPDATE menu set url = '/categoriaProfissional/gestao' where nome = 'Categorias Profissionais';
UPDATE menu set url = '/categoriaEconomica/gestao' where nome = 'Categoria Econômica';
UPDATE menu set url = '/cbo/gestao' where nome = 'CBOs';
UPDATE menu set url = '/cargo/gestao' where nome = 'Cargos';
UPDATE menu set url = '/classificacaoAgenteNocivo/gestao' where nome = 'Class. de Agentes Nocivos';
UPDATE menu set url = '/centroCusto/gestao' where nome = 'Centro de Custo';
UPDATE menu set url = '/cnae/gestao' where nome = 'CNAE';
UPDATE menu set url = '/correcaoSalarial/gestao' where nome = 'Correção Salarial';
UPDATE menu set url = '/vinculo/gestao' where nome = 'Vínculos';
UPDATE menu set url = '/contaContabilSimples/gestao' where nome = 'Contas Contábeis Simples';
UPDATE menu set url = '/convenio/gestao' where nome = 'Convênios';
UPDATE menu set url = '/regraAposentadoria/gestao' where nome = 'Regras de Aposentadoria';
UPDATE menu set url = '/equipamentoProtecaoIndividual/gestao' where nome = 'EPI';
UPDATE menu set url = '/consignado/gestao' where nome = 'Consignado';
UPDATE menu set url = '/equipamentoProtecaoColetiva/gestao' where nome = 'EPC';
UPDATE menu set url = '/evento/gestao' where nome = 'Evento';
UPDATE menu set url = '/etapa/gestao' where nome = 'Etapas';
UPDATE menu set url = '/entidadeExame/gestao' where nome = 'Entidades de Exames';
UPDATE menu set url = '/exame/gestao' where nome = 'Exames';
UPDATE menu set url = '/grauAcademico/gestao' where nome = 'Graus Acadêmicos';
UPDATE menu set url = '/faixaSalarial/gestao' where nome = 'Faixas Salariais';
UPDATE menu set url = '/curso/gestao' where nome = 'Cursos';
UPDATE menu set url = '/crmCrea/gestao' where nome = 'CRM / CREA';
UPDATE menu set url = '/afastamento/gestao' where nome = 'Afastamento';
UPDATE menu set url = '/causaAfastamento/gestao' where nome = 'Causas de Afastamento';
UPDATE menu set url = '/motivoAfastamento/gestao' where nome = 'Motivo Afastamento';
UPDATE menu set url = '/motivoDesligamento/gestao' where nome = 'Motivos do Desligamento';
UPDATE menu set url = '/codigoRecolhimento/gestao' where nome = 'Códigos do Recolhimento';
UPDATE menu set url = '/lotacao/gestao' where nome = 'Lotação';
UPDATE menu set url = '/funcao/gestao' where nome = 'Função';
UPDATE menu set url = '/motivo/gestao' where nome = 'Motivos';
UPDATE menu set url = '/codigoPagamentoGps/gestao' where nome = 'Códigos do Pagamento GPS';
UPDATE menu set url = '/habilidade/gestao' where nome = 'Habilidades';
UPDATE menu set url = '/nacionalidade/gestao' where nome = 'País';
UPDATE menu set url = '/municipio/gestao' where nome = 'Município';
UPDATE menu set url = '/tomadorServico/gestao' where nome = 'Tomador de Serviço';
UPDATE menu set url = '/unidadeFederativa/gestao' where nome = 'Unidades Federativas';
UPDATE menu set url = '/sefip/gestao' where nome = 'SEFIP';
UPDATE menu set url = '/requisito/gestao' where nome = 'Requisito';
UPDATE menu set url = '/esocial/gestao' where nome = 'eSocial';
UPDATE menu set url = '/tipoFerias/gestao' where nome = 'Tipos de Férias';
UPDATE menu set url = '/tipoFolha/gestao' where nome = 'Tipos de Folhas';
UPDATE menu set url = '/classificacaoBeneficio/gestao' where nome = 'Classificações dos Benefícios';
UPDATE menu set url = '/naturezaJuridica/gestao' where nome = 'Naturezas Jurídicas';
UPDATE menu set url = '/tipoContrato/gestao' where nome = 'Tipos de Contrato';
UPDATE menu set url = '/modeloDocumento/gestao' where nome = 'Modelo de Documento';
UPDATE menu set url = '/tipoAverbacao/gestao' where nome = 'Tipos de Averbações';
UPDATE menu set url = '/sindicato/gestao' where nome = 'Sindicatos';
UPDATE menu set url = '/tipoProcessamento/gestao' where nome = 'Tipo de Processamento';
UPDATE menu set url = '/empresaFilial/gestao' where nome = 'Empresa Filial';
UPDATE menu set url = '/valeTransporte/gestao' where nome = 'Vales Transporte';
UPDATE menu set url = '/historicoContabil/gestao' where nome = 'Histórico Contábil';
UPDATE menu set url = '/turno/gestao' where nome = 'Turno';
UPDATE menu set url = '/verba/gestao' where nome = 'Verbas';
UPDATE menu set url = '/diaUtil/gestao' where nome = 'Dia Util';
UPDATE menu set url = '/naturezaFuncao/gestao' where nome = 'Natureza da Função';
UPDATE menu set url = '/responsavelLegal/gestao' where nome = 'Responsável Legal';
UPDATE menu set url = '/nivelSalarial/gestao' where nome = 'Nível';
UPDATE menu set url = '/processoFuncao/gestao' where nome = 'Processo de Função';
UPDATE menu set url = '/prestadorServico/gestao' where nome = 'Prestadores de Serviço';
UPDATE menu set url = '/contaContabil/gestao' where nome = 'Conta Contábil';