-- Marconi Motta
-- alterar o campo historico_atual_id para NULL
ALTER TABLE relatorio_financeiro_folha_pagamento ALTER COLUMN historico_atual_id BIGINT  NULL;

ALTER TABLE relatorio_financeiro_folha_pagamento_filial DROP CONSTRAINT pk_relatorio_financeiro_folha_pagamento_filial_relatorio_id;

ALTER TABLE relatorio_financeiro_folha_pagamento_filial ADD CONSTRAINT pk_relatorio_financeiro_folha_pagamento_filial_relatorio_id PRIMARY KEY (relatorio_financeiro_folha_pagamento_id, empresa_filial_id);

ALTER TABLE relatorio_financeiro_folha_pagamento_lotacao DROP CONSTRAINT pk_relatorio_financeiro_folha_pagamento_lotacao_relatorio_id;

ALTER TABLE relatorio_financeiro_folha_pagamento_lotacao ADD CONSTRAINT pk_relatorio_financeiro_folha_pagamento_lotacao_relatorio_id PRIMARY KEY (relatorio_financeiro_folha_pagamento_id, lotacao_id);

ALTER TABLE relatorio_financeiro_folha_pagamento_situacao_funcional DROP CONSTRAINT pk_relatorio_financeiro_folha_pagamento_situacao_funcional_relatorio_id;

ALTER TABLE relatorio_financeiro_folha_pagamento_situacao_funcional ADD CONSTRAINT [pk_relatorio_financeiro_folha_pagamento_situacao_funcional_relatorio_id] PRIMARY KEY (relatorio_financeiro_folha_pagamento_id, situacao_funcional_id);