-- Flávio Silva
-- Inserts de todos os papeis padrões de cada menu do sistema.

-- Deletando os papeis inseridos anteriormente.
BEGIN

ALTER TABLE papel ALTER COLUMN nome varchar(255);

	
DELETE FROM perfil_papel WHERE papel_id = (SELECT p.id FROM papel p WHERE p.nome = 'ROLE_PERFIL_ACESSO_CADASTRAR');
DELETE FROM perfil_papel WHERE papel_id = (SELECT p.id FROM papel p WHERE p.nome = 'ROLE_PERFIL_ACESSO_ATUALIZAR');
DELETE FROM perfil_papel WHERE papel_id = (SELECT p.id FROM papel p WHERE p.nome = 'ROLE_PERFIL_ACESSO_EXCLUIR');
DELETE FROM perfil_papel WHERE papel_id = (SELECT p.id FROM papel p WHERE p.nome = 'ROLE_PERFIL_ACESSO_VISUALIZAR');

DELETE FROM perfil_papel WHERE papel_id = (SELECT p.id FROM papel p WHERE p.nome = 'ROLE_CERTIDAO_COMPENSACAO_CADASTRAR');
DELETE FROM perfil_papel WHERE papel_id = (SELECT p.id FROM papel p WHERE p.nome = 'ROLE_CERTIDAO_COMPENSACAO_ATUALIZAR');
DELETE FROM perfil_papel WHERE papel_id = (SELECT p.id FROM papel p WHERE p.nome = 'ROLE_CERTIDAO_COMPENSACAO_EXCLUIR');
DELETE FROM perfil_papel WHERE papel_id = (SELECT p.id FROM papel p WHERE p.nome = 'ROLE_CERTIDAO_COMPENSACAO_VISUALIZAR');

DELETE FROM usuario_papel WHERE papel_id = (SELECT p.id FROM papel p WHERE p.nome = 'ROLE_PERFIL_ACESSO_CADASTRAR');
DELETE FROM usuario_papel WHERE papel_id = (SELECT p.id FROM papel p WHERE p.nome = 'ROLE_PERFIL_ACESSO_ATUALIZAR');
DELETE FROM usuario_papel WHERE papel_id = (SELECT p.id FROM papel p WHERE p.nome = 'ROLE_PERFIL_ACESSO_EXCLUIR');
DELETE FROM usuario_papel WHERE papel_id = (SELECT p.id FROM papel p WHERE p.nome = 'ROLE_PERFIL_ACESSO_VISUALIZAR');

DELETE FROM usuario_papel WHERE papel_id = (SELECT p.id FROM papel p WHERE p.nome = 'ROLE_CERTIDAO_COMPENSACAO_CADASTRAR');
DELETE FROM usuario_papel WHERE papel_id = (SELECT p.id FROM papel p WHERE p.nome = 'ROLE_CERTIDAO_COMPENSACAO_ATUALIZAR');
DELETE FROM usuario_papel WHERE papel_id = (SELECT p.id FROM papel p WHERE p.nome = 'ROLE_CERTIDAO_COMPENSACAO_EXCLUIR');
DELETE FROM usuario_papel WHERE papel_id = (SELECT p.id FROM papel p WHERE p.nome = 'ROLE_CERTIDAO_COMPENSACAO_VISUALIZAR');

DELETE FROM papel WHERE nome = 'ROLE_PERFIL_ACESSO_CADASTRAR';
DELETE FROM papel WHERE nome = 'ROLE_PERFIL_ACESSO_ATUALIZAR';
DELETE FROM papel WHERE nome = 'ROLE_PERFIL_ACESSO_EXCLUIR';
DELETE FROM papel WHERE nome = 'ROLE_PERFIL_ACESSO_VISUALIZAR';

DELETE FROM papel WHERE nome = 'ROLE_CERTIDAO_COMPENSACAO_CADASTRAR';
DELETE FROM papel WHERE nome = 'ROLE_CERTIDAO_COMPENSACAO_ATUALIZAR';
DELETE FROM papel WHERE nome = 'ROLE_CERTIDAO_COMPENSACAO_EXCLUIR';
DELETE FROM papel WHERE nome = 'ROLE_CERTIDAO_COMPENSACAO_VISUALIZAR';

-- Inserindo os novos papeis padronizados.

IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_USUARIOS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_USUARIOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Usuários'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_USUARIOS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_USUARIOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Usuários'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_USUARIOS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_USUARIOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Usuários'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_USUARIOS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_USUARIOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Usuários'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_AREA_DE_FORMACAO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_AREA_DE_FORMACAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Área de Formação'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_AREA_DE_FORMACAO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_AREA_DE_FORMACAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Área de Formação'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_AREA_DE_FORMACAO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_AREA_DE_FORMACAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Área de Formação'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_AREA_DE_FORMACAO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_AREA_DE_FORMACAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Área de Formação'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_BANCOS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_BANCOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Bancos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_BANCOS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_BANCOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Bancos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_BANCOS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_BANCOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Bancos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_BANCOS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_BANCOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Bancos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ATIVIDADE_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ATIVIDADE_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Atividade'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ATIVIDADE_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ATIVIDADE_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Atividade'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ATIVIDADE_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ATIVIDADE_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Atividade'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ATIVIDADE_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ATIVIDADE_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Atividade'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CATEGORIAS_PROFISSIONAIS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CATEGORIAS_PROFISSIONAIS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Categorias Profissionais'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CATEGORIAS_PROFISSIONAIS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CATEGORIAS_PROFISSIONAIS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Categorias Profissionais'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CATEGORIAS_PROFISSIONAIS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CATEGORIAS_PROFISSIONAIS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Categorias Profissionais'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CATEGORIAS_PROFISSIONAIS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CATEGORIAS_PROFISSIONAIS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Categorias Profissionais'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CATEGORIAS_DE_DOENCAS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CATEGORIAS_DE_DOENCAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Categorias de Doenças'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CATEGORIAS_DE_DOENCAS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CATEGORIAS_DE_DOENCAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Categorias de Doenças'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CATEGORIAS_DE_DOENCAS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CATEGORIAS_DE_DOENCAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Categorias de Doenças'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CATEGORIAS_DE_DOENCAS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CATEGORIAS_DE_DOENCAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Categorias de Doenças'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CATEGORIA_ECONOMICA_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CATEGORIA_ECONOMICA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Categoria Econômica'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CATEGORIA_ECONOMICA_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CATEGORIA_ECONOMICA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Categoria Econômica'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CATEGORIA_ECONOMICA_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CATEGORIA_ECONOMICA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Categoria Econômica'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CATEGORIA_ECONOMICA_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CATEGORIA_ECONOMICA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Categoria Econômica'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CBOS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CBOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'CBOs'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CBOS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CBOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'CBOs'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CBOS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CBOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'CBOs'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CBOS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CBOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'CBOs'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CLASS_DE_AGENTES_NOCIVOS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CLASS_DE_AGENTES_NOCIVOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Class. de Agentes Nocivos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CLASS_DE_AGENTES_NOCIVOS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CLASS_DE_AGENTES_NOCIVOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Class. de Agentes Nocivos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CLASS_DE_AGENTES_NOCIVOS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CLASS_DE_AGENTES_NOCIVOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Class. de Agentes Nocivos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CLASS_DE_AGENTES_NOCIVOS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CLASS_DE_AGENTES_NOCIVOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Class. de Agentes Nocivos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_SUBCATEGORIAS_DE_DOENCAS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_SUBCATEGORIAS_DE_DOENCAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Subcategorias de Doenças'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_SUBCATEGORIAS_DE_DOENCAS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_SUBCATEGORIAS_DE_DOENCAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Subcategorias de Doenças'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_SUBCATEGORIAS_DE_DOENCAS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_SUBCATEGORIAS_DE_DOENCAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Subcategorias de Doenças'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_SUBCATEGORIAS_DE_DOENCAS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_SUBCATEGORIAS_DE_DOENCAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Subcategorias de Doenças'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CENTRO_DE_CUSTO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CENTRO_DE_CUSTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Centro de Custo'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CENTRO_DE_CUSTO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CENTRO_DE_CUSTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Centro de Custo'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CENTRO_DE_CUSTO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CENTRO_DE_CUSTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Centro de Custo'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CENTRO_DE_CUSTO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CENTRO_DE_CUSTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Centro de Custo'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CLASSIFICACAO_DE_DOENCAS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CLASSIFICACAO_DE_DOENCAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Classificação de Doenças'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CLASSIFICACAO_DE_DOENCAS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CLASSIFICACAO_DE_DOENCAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Classificação de Doenças'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CLASSIFICACAO_DE_DOENCAS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CLASSIFICACAO_DE_DOENCAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Classificação de Doenças'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CLASSIFICACAO_DE_DOENCAS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CLASSIFICACAO_DE_DOENCAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Classificação de Doenças'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CNAE_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CNAE_CADASTRAR', (SELECT id FROM menu WHERE nome = 'CNAE'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CNAE_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CNAE_CADASTRAR', (SELECT id FROM menu WHERE nome = 'CNAE'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CNAE_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CNAE_CADASTRAR', (SELECT id FROM menu WHERE nome = 'CNAE'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CNAE_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CNAE_CADASTRAR', (SELECT id FROM menu WHERE nome = 'CNAE'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CONTAS_CONTABEIS_SIMPLES_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CONTAS_CONTABEIS_SIMPLES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Contas Contábeis Simples'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CONTAS_CONTABEIS_SIMPLES_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CONTAS_CONTABEIS_SIMPLES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Contas Contábeis Simples'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CONTAS_CONTABEIS_SIMPLES_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CONTAS_CONTABEIS_SIMPLES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Contas Contábeis Simples'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CONTAS_CONTABEIS_SIMPLES_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CONTAS_CONTABEIS_SIMPLES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Contas Contábeis Simples'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CONVENIOS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CONVENIOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Convênios'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CONVENIOS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CONVENIOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Convênios'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CONVENIOS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CONVENIOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Convênios'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CONVENIOS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CONVENIOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Convênios'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_REGRAS_DE_APOSENTADORIA_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_REGRAS_DE_APOSENTADORIA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Regras de Aposentadoria'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_REGRAS_DE_APOSENTADORIA_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_REGRAS_DE_APOSENTADORIA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Regras de Aposentadoria'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_REGRAS_DE_APOSENTADORIA_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_REGRAS_DE_APOSENTADORIA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Regras de Aposentadoria'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_REGRAS_DE_APOSENTADORIA_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_REGRAS_DE_APOSENTADORIA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Regras de Aposentadoria'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CONSIGNADO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CONSIGNADO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Consignado'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CONSIGNADO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CONSIGNADO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Consignado'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CONSIGNADO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CONSIGNADO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Consignado'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CONSIGNADO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CONSIGNADO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Consignado'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_EPI_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_EPI_CADASTRAR', (SELECT id FROM menu WHERE nome = 'EPI'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_EPI_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_EPI_CADASTRAR', (SELECT id FROM menu WHERE nome = 'EPI'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_EPI_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_EPI_CADASTRAR', (SELECT id FROM menu WHERE nome = 'EPI'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_EPI_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_EPI_CADASTRAR', (SELECT id FROM menu WHERE nome = 'EPI'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_EPC_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_EPC_CADASTRAR', (SELECT id FROM menu WHERE nome = 'EPC'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_EPC_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_EPC_CADASTRAR', (SELECT id FROM menu WHERE nome = 'EPC'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_EPC_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_EPC_CADASTRAR', (SELECT id FROM menu WHERE nome = 'EPC'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_EPC_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_EPC_CADASTRAR', (SELECT id FROM menu WHERE nome = 'EPC'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_EVENTO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_EVENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Evento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_EVENTO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_EVENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Evento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_EVENTO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_EVENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Evento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_EVENTO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_EVENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Evento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ETAPAS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ETAPAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Etapas'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ETAPAS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ETAPAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Etapas'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ETAPAS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ETAPAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Etapas'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ETAPAS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ETAPAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Etapas'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_EXAMES_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_EXAMES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Exames'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_EXAMES_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_EXAMES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Exames'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_EXAMES_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_EXAMES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Exames'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_EXAMES_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_EXAMES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Exames'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_GRAUS_ACADEMICOS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_GRAUS_ACADEMICOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Graus Acadêmicos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_GRAUS_ACADEMICOS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_GRAUS_ACADEMICOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Graus Acadêmicos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_GRAUS_ACADEMICOS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_GRAUS_ACADEMICOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Graus Acadêmicos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_GRAUS_ACADEMICOS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_GRAUS_ACADEMICOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Graus Acadêmicos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_FAIXAS_SALARIAIS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_FAIXAS_SALARIAIS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Faixas Salariais'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_FAIXAS_SALARIAIS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_FAIXAS_SALARIAIS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Faixas Salariais'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_FAIXAS_SALARIAIS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_FAIXAS_SALARIAIS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Faixas Salariais'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_FAIXAS_SALARIAIS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_FAIXAS_SALARIAIS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Faixas Salariais'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CURSOS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CURSOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Cursos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CURSOS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CURSOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Cursos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CURSOS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CURSOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Cursos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CURSOS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CURSOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Cursos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_SITUACAO_FUNCIONAL_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_SITUACAO_FUNCIONAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Situação Funcional'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_SITUACAO_FUNCIONAL_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_SITUACAO_FUNCIONAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Situação Funcional'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_SITUACAO_FUNCIONAL_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_SITUACAO_FUNCIONAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Situação Funcional'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_SITUACAO_FUNCIONAL_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_SITUACAO_FUNCIONAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Situação Funcional'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CRM_CREA_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CRM_CREA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'CRM / CREA'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CRM_CREA_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CRM_CREA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'CRM / CREA'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CRM_CREA_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CRM_CREA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'CRM / CREA'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CRM_CREA_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CRM_CREA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'CRM / CREA'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CAUSAS_DE_AFASTAMENTO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CAUSAS_DE_AFASTAMENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Causas de Afastamento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CAUSAS_DE_AFASTAMENTO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CAUSAS_DE_AFASTAMENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Causas de Afastamento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CAUSAS_DE_AFASTAMENTO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CAUSAS_DE_AFASTAMENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Causas de Afastamento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CAUSAS_DE_AFASTAMENTO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CAUSAS_DE_AFASTAMENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Causas de Afastamento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_MOTIVO_AFASTAMENTO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_MOTIVO_AFASTAMENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Motivo Afastamento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_MOTIVO_AFASTAMENTO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_MOTIVO_AFASTAMENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Motivo Afastamento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_MOTIVO_AFASTAMENTO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_MOTIVO_AFASTAMENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Motivo Afastamento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_MOTIVO_AFASTAMENTO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_MOTIVO_AFASTAMENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Motivo Afastamento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_MOTIVOS_DO_DESLIGAMENTO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_MOTIVOS_DO_DESLIGAMENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Motivos do Desligamento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_MOTIVOS_DO_DESLIGAMENTO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_MOTIVOS_DO_DESLIGAMENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Motivos do Desligamento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_MOTIVOS_DO_DESLIGAMENTO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_MOTIVOS_DO_DESLIGAMENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Motivos do Desligamento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_MOTIVOS_DO_DESLIGAMENTO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_MOTIVOS_DO_DESLIGAMENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Motivos do Desligamento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CODIGOS_DO_RECOLHIMENTO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CODIGOS_DO_RECOLHIMENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Códigos do Recolhimento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CODIGOS_DO_RECOLHIMENTO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CODIGOS_DO_RECOLHIMENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Códigos do Recolhimento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CODIGOS_DO_RECOLHIMENTO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CODIGOS_DO_RECOLHIMENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Códigos do Recolhimento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CODIGOS_DO_RECOLHIMENTO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CODIGOS_DO_RECOLHIMENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Códigos do Recolhimento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CODIGOS_DO_PAGAMENTO_GPS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CODIGOS_DO_PAGAMENTO_GPS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Códigos do Pagamento GPS'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CODIGOS_DO_PAGAMENTO_GPS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CODIGOS_DO_PAGAMENTO_GPS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Códigos do Pagamento GPS'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CODIGOS_DO_PAGAMENTO_GPS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CODIGOS_DO_PAGAMENTO_GPS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Códigos do Pagamento GPS'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CODIGOS_DO_PAGAMENTO_GPS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CODIGOS_DO_PAGAMENTO_GPS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Códigos do Pagamento GPS'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_MOTIVOS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_MOTIVOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Motivos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_MOTIVOS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_MOTIVOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Motivos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_MOTIVOS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_MOTIVOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Motivos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_MOTIVOS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_MOTIVOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Motivos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_LOTACAO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_LOTACAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Lotação'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_LOTACAO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_LOTACAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Lotação'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_LOTACAO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_LOTACAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Lotação'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_LOTACAO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_LOTACAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Lotação'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_HABILIDADES_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_HABILIDADES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Habilidades'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_HABILIDADES_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_HABILIDADES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Habilidades'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_HABILIDADES_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_HABILIDADES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Habilidades'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_HABILIDADES_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_HABILIDADES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Habilidades'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PAIS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PAIS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'País'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PAIS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PAIS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'País'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PAIS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PAIS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'País'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PAIS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PAIS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'País'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_MUNICIPIO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_MUNICIPIO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Município'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_MUNICIPIO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_MUNICIPIO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Município'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_MUNICIPIO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_MUNICIPIO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Município'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_MUNICIPIO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_MUNICIPIO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Município'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TOMADOR_DE_SERVICO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TOMADOR_DE_SERVICO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tomador de Serviço'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TOMADOR_DE_SERVICO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TOMADOR_DE_SERVICO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tomador de Serviço'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TOMADOR_DE_SERVICO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TOMADOR_DE_SERVICO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tomador de Serviço'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TOMADOR_DE_SERVICO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TOMADOR_DE_SERVICO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tomador de Serviço'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_UNIDADES_FEDERATIVAS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_UNIDADES_FEDERATIVAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Unidades Federativas'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_UNIDADES_FEDERATIVAS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_UNIDADES_FEDERATIVAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Unidades Federativas'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_UNIDADES_FEDERATIVAS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_UNIDADES_FEDERATIVAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Unidades Federativas'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_UNIDADES_FEDERATIVAS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_UNIDADES_FEDERATIVAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Unidades Federativas'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_SEFIP_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_SEFIP_CADASTRAR', (SELECT id FROM menu WHERE nome = 'SEFIP'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_SEFIP_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_SEFIP_CADASTRAR', (SELECT id FROM menu WHERE nome = 'SEFIP'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_SEFIP_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_SEFIP_CADASTRAR', (SELECT id FROM menu WHERE nome = 'SEFIP'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_SEFIP_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_SEFIP_CADASTRAR', (SELECT id FROM menu WHERE nome = 'SEFIP'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ESOCIAL_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ESOCIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'eSocial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ESOCIAL_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ESOCIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'eSocial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ESOCIAL_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ESOCIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'eSocial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ESOCIAL_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ESOCIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'eSocial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TIPOS_DE_FERIAS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TIPOS_DE_FERIAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tipos de Férias'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TIPOS_DE_FERIAS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TIPOS_DE_FERIAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tipos de Férias'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TIPOS_DE_FERIAS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TIPOS_DE_FERIAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tipos de Férias'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TIPOS_DE_FERIAS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TIPOS_DE_FERIAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tipos de Férias'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TIPOS_DE_FOLHAS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TIPOS_DE_FOLHAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tipos de Folhas'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TIPOS_DE_FOLHAS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TIPOS_DE_FOLHAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tipos de Folhas'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TIPOS_DE_FOLHAS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TIPOS_DE_FOLHAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tipos de Folhas'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TIPOS_DE_FOLHAS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TIPOS_DE_FOLHAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tipos de Folhas'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CLASSIFICACOES_DOS_ATOS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CLASSIFICACOES_DOS_ATOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Classificações dos Atos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CLASSIFICACOES_DOS_ATOS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CLASSIFICACOES_DOS_ATOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Classificações dos Atos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CLASSIFICACOES_DOS_ATOS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CLASSIFICACOES_DOS_ATOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Classificações dos Atos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CLASSIFICACOES_DOS_ATOS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CLASSIFICACOES_DOS_ATOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Classificações dos Atos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_NATUREZAS_JURIDICAS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_NATUREZAS_JURIDICAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Naturezas Jurídicas'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_NATUREZAS_JURIDICAS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_NATUREZAS_JURIDICAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Naturezas Jurídicas'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_NATUREZAS_JURIDICAS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_NATUREZAS_JURIDICAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Naturezas Jurídicas'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_NATUREZAS_JURIDICAS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_NATUREZAS_JURIDICAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Naturezas Jurídicas'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TIPOS_DE_CONTRATO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TIPOS_DE_CONTRATO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tipos de Contrato'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TIPOS_DE_CONTRATO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TIPOS_DE_CONTRATO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tipos de Contrato'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TIPOS_DE_CONTRATO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TIPOS_DE_CONTRATO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tipos de Contrato'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TIPOS_DE_CONTRATO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TIPOS_DE_CONTRATO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tipos de Contrato'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TIPOS_DE_AVERBACOES_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TIPOS_DE_AVERBACOES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tipos de Averbações'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TIPOS_DE_AVERBACOES_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TIPOS_DE_AVERBACOES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tipos de Averbações'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TIPOS_DE_AVERBACOES_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TIPOS_DE_AVERBACOES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tipos de Averbações'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TIPOS_DE_AVERBACOES_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TIPOS_DE_AVERBACOES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tipos de Averbações'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_MODELO_DE_DOCUMENTO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_MODELO_DE_DOCUMENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Modelo de Documento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_MODELO_DE_DOCUMENTO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_MODELO_DE_DOCUMENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Modelo de Documento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_MODELO_DE_DOCUMENTO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_MODELO_DE_DOCUMENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Modelo de Documento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_MODELO_DE_DOCUMENTO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_MODELO_DE_DOCUMENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Modelo de Documento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_EMPRESA_FILIAL_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_EMPRESA_FILIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Empresa Filial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_EMPRESA_FILIAL_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_EMPRESA_FILIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Empresa Filial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_EMPRESA_FILIAL_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_EMPRESA_FILIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Empresa Filial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_EMPRESA_FILIAL_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_EMPRESA_FILIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Empresa Filial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_SINDICATOS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_SINDICATOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Sindicatos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_SINDICATOS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_SINDICATOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Sindicatos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_SINDICATOS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_SINDICATOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Sindicatos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_SINDICATOS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_SINDICATOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Sindicatos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_VERBAS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_VERBAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Verbas'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_VERBAS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_VERBAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Verbas'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_VERBAS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_VERBAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Verbas'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_VERBAS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_VERBAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Verbas'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TIPO_DE_PROCESSAMENTO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TIPO_DE_PROCESSAMENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tipo de Processamento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TIPO_DE_PROCESSAMENTO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TIPO_DE_PROCESSAMENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tipo de Processamento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TIPO_DE_PROCESSAMENTO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TIPO_DE_PROCESSAMENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tipo de Processamento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TIPO_DE_PROCESSAMENTO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TIPO_DE_PROCESSAMENTO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tipo de Processamento'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_VALES_TRANSPORTE_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_VALES_TRANSPORTE_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Vales Transporte'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_VALES_TRANSPORTE_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_VALES_TRANSPORTE_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Vales Transporte'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_VALES_TRANSPORTE_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_VALES_TRANSPORTE_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Vales Transporte'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_VALES_TRANSPORTE_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_VALES_TRANSPORTE_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Vales Transporte'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_HISTORICO_CONTABIL_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_HISTORICO_CONTABIL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Histórico Contábil'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_HISTORICO_CONTABIL_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_HISTORICO_CONTABIL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Histórico Contábil'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_HISTORICO_CONTABIL_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_HISTORICO_CONTABIL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Histórico Contábil'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_HISTORICO_CONTABIL_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_HISTORICO_CONTABIL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Histórico Contábil'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ENTIDADES_DE_EXAMES_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ENTIDADES_DE_EXAMES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Entidades de Exames'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ENTIDADES_DE_EXAMES_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ENTIDADES_DE_EXAMES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Entidades de Exames'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ENTIDADES_DE_EXAMES_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ENTIDADES_DE_EXAMES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Entidades de Exames'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ENTIDADES_DE_EXAMES_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ENTIDADES_DE_EXAMES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Entidades de Exames'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TURNO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TURNO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Turno'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TURNO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TURNO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Turno'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TURNO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TURNO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Turno'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TURNO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TURNO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Turno'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_RESPONSAVEL_LEGAL_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_RESPONSAVEL_LEGAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Responsável Legal'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_RESPONSAVEL_LEGAL_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_RESPONSAVEL_LEGAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Responsável Legal'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_RESPONSAVEL_LEGAL_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_RESPONSAVEL_LEGAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Responsável Legal'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_RESPONSAVEL_LEGAL_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_RESPONSAVEL_LEGAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Responsável Legal'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_REQUISITO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_REQUISITO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Requisito'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_REQUISITO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_REQUISITO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Requisito'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_REQUISITO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_REQUISITO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Requisito'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_REQUISITO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_REQUISITO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Requisito'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_NATUREZA_DA_FUNCAO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_NATUREZA_DA_FUNCAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Natureza da Função'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_NATUREZA_DA_FUNCAO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_NATUREZA_DA_FUNCAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Natureza da Função'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_NATUREZA_DA_FUNCAO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_NATUREZA_DA_FUNCAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Natureza da Função'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_NATUREZA_DA_FUNCAO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_NATUREZA_DA_FUNCAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Natureza da Função'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_VINCULOS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_VINCULOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Vínculos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_VINCULOS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_VINCULOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Vínculos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_VINCULOS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_VINCULOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Vínculos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_VINCULOS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_VINCULOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Vínculos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_REFERENCIA_SALARIAL_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_REFERENCIA_SALARIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Referência Salarial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_REFERENCIA_SALARIAL_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_REFERENCIA_SALARIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Referência Salarial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_REFERENCIA_SALARIAL_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_REFERENCIA_SALARIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Referência Salarial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_REFERENCIA_SALARIAL_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_REFERENCIA_SALARIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Referência Salarial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PROCESSO_DE_FUNCAO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PROCESSO_DE_FUNCAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Processo de Função'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PROCESSO_DE_FUNCAO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PROCESSO_DE_FUNCAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Processo de Função'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PROCESSO_DE_FUNCAO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PROCESSO_DE_FUNCAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Processo de Função'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PROCESSO_DE_FUNCAO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PROCESSO_DE_FUNCAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Processo de Função'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DIA_UTIL_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DIA_UTIL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Dia Util'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DIA_UTIL_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DIA_UTIL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Dia Util'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DIA_UTIL_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DIA_UTIL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Dia Util'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DIA_UTIL_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DIA_UTIL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Dia Util'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_FUNCAO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_FUNCAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Função'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_FUNCAO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_FUNCAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Função'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_FUNCAO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_FUNCAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Função'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_FUNCAO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_FUNCAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Função'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PRESTADORES_DE_SERVICO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PRESTADORES_DE_SERVICO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Prestadores de Serviço'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PRESTADORES_DE_SERVICO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PRESTADORES_DE_SERVICO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Prestadores de Serviço'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PRESTADORES_DE_SERVICO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PRESTADORES_DE_SERVICO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Prestadores de Serviço'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PRESTADORES_DE_SERVICO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PRESTADORES_DE_SERVICO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Prestadores de Serviço'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CORRECAO_SALARIAL_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CORRECAO_SALARIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Correção Salarial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CORRECAO_SALARIAL_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CORRECAO_SALARIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Correção Salarial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CORRECAO_SALARIAL_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CORRECAO_SALARIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Correção Salarial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CORRECAO_SALARIAL_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CORRECAO_SALARIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Correção Salarial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CARGOS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CARGOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Cargos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CARGOS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CARGOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Cargos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CARGOS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CARGOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Cargos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CARGOS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CARGOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Cargos'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CONTA_CONTABIL_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CONTA_CONTABIL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Conta Contábil'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CONTA_CONTABIL_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CONTA_CONTABIL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Conta Contábil'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CONTA_CONTABIL_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CONTA_CONTABIL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Conta Contábil'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CONTA_CONTABIL_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CONTA_CONTABIL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Conta Contábil'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_FUNCIONARIO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_FUNCIONARIO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Funcionário'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_FUNCIONARIO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_FUNCIONARIO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Funcionário'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_FUNCIONARIO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_FUNCIONARIO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Funcionário'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_FUNCIONARIO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_FUNCIONARIO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Funcionário'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DEPENDENTES_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DEPENDENTES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Dependentes'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DEPENDENTES_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DEPENDENTES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Dependentes'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DEPENDENTES_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DEPENDENTES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Dependentes'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DEPENDENTES_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DEPENDENTES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Dependentes'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_SIMU_NIVEL_SALARIAL_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_SIMU_NIVEL_SALARIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Simu. Nível Salarial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_SIMU_NIVEL_SALARIAL_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_SIMU_NIVEL_SALARIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Simu. Nível Salarial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_SIMU_NIVEL_SALARIAL_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_SIMU_NIVEL_SALARIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Simu. Nível Salarial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_SIMU_NIVEL_SALARIAL_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_SIMU_NIVEL_SALARIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Simu. Nível Salarial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DEFINICAO_DE_ORGANICO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DEFINICAO_DE_ORGANICO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Definição de Orgânico'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DEFINICAO_DE_ORGANICO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DEFINICAO_DE_ORGANICO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Definição de Orgânico'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DEFINICAO_DE_ORGANICO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DEFINICAO_DE_ORGANICO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Definição de Orgânico'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DEFINICAO_DE_ORGANICO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DEFINICAO_DE_ORGANICO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Definição de Orgânico'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CONTRIBUICAO_SINDICAL_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CONTRIBUICAO_SINDICAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Contribuição Sindical'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CONTRIBUICAO_SINDICAL_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CONTRIBUICAO_SINDICAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Contribuição Sindical'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CONTRIBUICAO_SINDICAL_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CONTRIBUICAO_SINDICAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Contribuição Sindical'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CONTRIBUICAO_SINDICAL_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CONTRIBUICAO_SINDICAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Contribuição Sindical'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DADOS_CADASTRAIS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DADOS_CADASTRAIS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Dados Cadastrais'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DADOS_CADASTRAIS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DADOS_CADASTRAIS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Dados Cadastrais'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DADOS_CADASTRAIS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DADOS_CADASTRAIS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Dados Cadastrais'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DADOS_CADASTRAIS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DADOS_CADASTRAIS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Dados Cadastrais'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_HIST_NIVEL_SALARIAL_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_HIST_NIVEL_SALARIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Hist. Nível Salarial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_HIST_NIVEL_SALARIAL_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_HIST_NIVEL_SALARIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Hist. Nível Salarial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_HIST_NIVEL_SALARIAL_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_HIST_NIVEL_SALARIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Hist. Nível Salarial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_HIST_NIVEL_SALARIAL_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_HIST_NIVEL_SALARIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Hist. Nível Salarial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_LICENCA_MEDICA_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_LICENCA_MEDICA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Licenca Médica'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_LICENCA_MEDICA_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_LICENCA_MEDICA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Licenca Médica'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_LICENCA_MEDICA_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_LICENCA_MEDICA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Licenca Médica'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_LICENCA_MEDICA_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_LICENCA_MEDICA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Licenca Médica'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DOSSIE_DO_SERVIDOR_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DOSSIE_DO_SERVIDOR_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Dossiê do Servidor'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DOSSIE_DO_SERVIDOR_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DOSSIE_DO_SERVIDOR_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Dossiê do Servidor'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DOSSIE_DO_SERVIDOR_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DOSSIE_DO_SERVIDOR_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Dossiê do Servidor'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DOSSIE_DO_SERVIDOR_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DOSSIE_DO_SERVIDOR_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Dossiê do Servidor'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TRANSFERENCIA_FUNCIONARIO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TRANSFERENCIA_FUNCIONARIO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Transferência Funcionário'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TRANSFERENCIA_FUNCIONARIO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TRANSFERENCIA_FUNCIONARIO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Transferência Funcionário'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TRANSFERENCIA_FUNCIONARIO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TRANSFERENCIA_FUNCIONARIO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Transferência Funcionário'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TRANSFERENCIA_FUNCIONARIO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TRANSFERENCIA_FUNCIONARIO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Transferência Funcionário'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PROCESSO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PROCESSO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Processo'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PROCESSO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PROCESSO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Processo'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PROCESSO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PROCESSO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Processo'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PROCESSO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PROCESSO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Processo'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_EXPERIENCIA_PROFISSIONAL_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_EXPERIENCIA_PROFISSIONAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Experiência Profissional'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_EXPERIENCIA_PROFISSIONAL_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_EXPERIENCIA_PROFISSIONAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Experiência Profissional'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_EXPERIENCIA_PROFISSIONAL_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_EXPERIENCIA_PROFISSIONAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Experiência Profissional'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_EXPERIENCIA_PROFISSIONAL_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_EXPERIENCIA_PROFISSIONAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Experiência Profissional'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ACIDENTE_DE_TRABALHO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ACIDENTE_DE_TRABALHO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Acidente de Trabalho'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ACIDENTE_DE_TRABALHO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ACIDENTE_DE_TRABALHO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Acidente de Trabalho'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ACIDENTE_DE_TRABALHO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ACIDENTE_DE_TRABALHO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Acidente de Trabalho'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ACIDENTE_DE_TRABALHO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ACIDENTE_DE_TRABALHO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Acidente de Trabalho'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TEMPO_DE_SERVICO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TEMPO_DE_SERVICO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tempo de Serviço'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TEMPO_DE_SERVICO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TEMPO_DE_SERVICO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tempo de Serviço'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TEMPO_DE_SERVICO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TEMPO_DE_SERVICO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tempo de Serviço'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TEMPO_DE_SERVICO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TEMPO_DE_SERVICO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tempo de Serviço'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_LICENCA_PREMIO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_LICENCA_PREMIO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Licença Prêmio'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_LICENCA_PREMIO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_LICENCA_PREMIO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Licença Prêmio'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_LICENCA_PREMIO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_LICENCA_PREMIO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Licença Prêmio'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_LICENCA_PREMIO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_LICENCA_PREMIO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Licença Prêmio'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PENSAO_ALIMENTICIA_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PENSAO_ALIMENTICIA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Pensão Alimentícia'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PENSAO_ALIMENTICIA_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PENSAO_ALIMENTICIA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Pensão Alimentícia'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PENSAO_ALIMENTICIA_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PENSAO_ALIMENTICIA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Pensão Alimentícia'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PENSAO_ALIMENTICIA_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PENSAO_ALIMENTICIA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Pensão Alimentícia'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ALIQUOTAS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ALIQUOTAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Alíquotas'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ALIQUOTAS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ALIQUOTAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Alíquotas'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ALIQUOTAS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ALIQUOTAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Alíquotas'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ALIQUOTAS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ALIQUOTAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Alíquotas'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_HISTORICO_SITUACAO_FUNCIONAL_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_HISTORICO_SITUACAO_FUNCIONAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Histórico Situação Funcional'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_HISTORICO_SITUACAO_FUNCIONAL_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_HISTORICO_SITUACAO_FUNCIONAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Histórico Situação Funcional'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_HISTORICO_SITUACAO_FUNCIONAL_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_HISTORICO_SITUACAO_FUNCIONAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Histórico Situação Funcional'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_HISTORICO_SITUACAO_FUNCIONAL_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_HISTORICO_SITUACAO_FUNCIONAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Histórico Situação Funcional'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PROGRAM_DE_FERIAS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PROGRAM_DE_FERIAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Program. de Férias'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PROGRAM_DE_FERIAS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PROGRAM_DE_FERIAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Program. de Férias'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PROGRAM_DE_FERIAS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PROGRAM_DE_FERIAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Program. de Férias'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PROGRAM_DE_FERIAS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PROGRAM_DE_FERIAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Program. de Férias'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_REG_DE_FREQUECIA_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_REG_DE_FREQUECIA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Reg. de Frequêcia'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_REG_DE_FREQUECIA_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_REG_DE_FREQUECIA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Reg. de Frequêcia'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_REG_DE_FREQUECIA_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_REG_DE_FREQUECIA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Reg. de Frequêcia'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_REG_DE_FREQUECIA_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_REG_DE_FREQUECIA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Reg. de Frequêcia'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_VERBAS_DO_FUNCIONARIO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_VERBAS_DO_FUNCIONARIO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Verbas do Funcionário'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_VERBAS_DO_FUNCIONARIO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_VERBAS_DO_FUNCIONARIO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Verbas do Funcionário'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_VERBAS_DO_FUNCIONARIO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_VERBAS_DO_FUNCIONARIO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Verbas do Funcionário'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_VERBAS_DO_FUNCIONARIO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_VERBAS_DO_FUNCIONARIO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Verbas do Funcionário'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_RESCISAO_CONTRATO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_RESCISAO_CONTRATO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Rescisão contrato'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_RESCISAO_CONTRATO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_RESCISAO_CONTRATO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Rescisão contrato'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_RESCISAO_CONTRATO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_RESCISAO_CONTRATO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Rescisão contrato'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_RESCISAO_CONTRATO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_RESCISAO_CONTRATO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Rescisão contrato'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_FOLHA_DE_PGT_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_FOLHA_DE_PGT_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Folha de Pgt'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_FOLHA_DE_PGT_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_FOLHA_DE_PGT_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Folha de Pgt'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_FOLHA_DE_PGT_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_FOLHA_DE_PGT_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Folha de Pgt'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_FOLHA_DE_PGT_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_FOLHA_DE_PGT_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Folha de Pgt'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_FICHA_FINANCEIRA_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_FICHA_FINANCEIRA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Ficha Financeira'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_FICHA_FINANCEIRA_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_FICHA_FINANCEIRA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Ficha Financeira'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_FICHA_FINANCEIRA_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_FICHA_FINANCEIRA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Ficha Financeira'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_FICHA_FINANCEIRA_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_FICHA_FINANCEIRA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Ficha Financeira'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ADIANTAMENTO_SALARIAL_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ADIANTAMENTO_SALARIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Adiantamento Salarial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ADIANTAMENTO_SALARIAL_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ADIANTAMENTO_SALARIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Adiantamento Salarial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ADIANTAMENTO_SALARIAL_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ADIANTAMENTO_SALARIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Adiantamento Salarial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_ADIANTAMENTO_SALARIAL_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_ADIANTAMENTO_SALARIAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Adiantamento Salarial'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_REQUISICAO_DE_PESSOAL_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_REQUISICAO_DE_PESSOAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Requisição de Pessoal'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_REQUISICAO_DE_PESSOAL_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_REQUISICAO_DE_PESSOAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Requisição de Pessoal'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_REQUISICAO_DE_PESSOAL_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_REQUISICAO_DE_PESSOAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Requisição de Pessoal'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_REQUISICAO_DE_PESSOAL_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_REQUISICAO_DE_PESSOAL_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Requisição de Pessoal'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_GESTAO_DE_AVALIACAO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_GESTAO_DE_AVALIACAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Gestão de Avaliação'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_GESTAO_DE_AVALIACAO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_GESTAO_DE_AVALIACAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Gestão de Avaliação'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_GESTAO_DE_AVALIACAO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_GESTAO_DE_AVALIACAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Gestão de Avaliação'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_GESTAO_DE_AVALIACAO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_GESTAO_DE_AVALIACAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Gestão de Avaliação'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PROGRAMACAO_DE_ADIANTAMENTO_DE_13º_SALARIO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PROGRAMACAO_DE_ADIANTAMENTO_DE_13º_SALARIO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Programação de Adiantamento de 13º Salário'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PROGRAMACAO_DE_ADIANTAMENTO_DE_13º_SALARIO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PROGRAMACAO_DE_ADIANTAMENTO_DE_13º_SALARIO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Programação de Adiantamento de 13º Salário'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PROGRAMACAO_DE_ADIANTAMENTO_DE_13º_SALARIO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PROGRAMACAO_DE_ADIANTAMENTO_DE_13º_SALARIO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Programação de Adiantamento de 13º Salário'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PROGRAMACAO_DE_ADIANTAMENTO_DE_13º_SALARIO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PROGRAMACAO_DE_ADIANTAMENTO_DE_13º_SALARIO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Programação de Adiantamento de 13º Salário'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TREINAMENTO_SUGERIDO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TREINAMENTO_SUGERIDO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Treinamento Sugerido'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TREINAMENTO_SUGERIDO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TREINAMENTO_SUGERIDO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Treinamento Sugerido'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TREINAMENTO_SUGERIDO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TREINAMENTO_SUGERIDO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Treinamento Sugerido'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TREINAMENTO_SUGERIDO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TREINAMENTO_SUGERIDO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Treinamento Sugerido'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_GESTAO_DE_REQUISICOES_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_GESTAO_DE_REQUISICOES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Gestão de Requisições'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_GESTAO_DE_REQUISICOES_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_GESTAO_DE_REQUISICOES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Gestão de Requisições'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_GESTAO_DE_REQUISICOES_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_GESTAO_DE_REQUISICOES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Gestão de Requisições'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_GESTAO_DE_REQUISICOES_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_GESTAO_DE_REQUISICOES_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Gestão de Requisições'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_RELATORIOS_GERENCIAIS_DO_RECRUTAMENTO_E_SELECAO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_RELATORIOS_GERENCIAIS_DO_RECRUTAMENTO_E_SELECAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Relatórios Gerenciais do Recrutamento e Seleção'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_RELATORIOS_GERENCIAIS_DO_RECRUTAMENTO_E_SELECAO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_RELATORIOS_GERENCIAIS_DO_RECRUTAMENTO_E_SELECAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Relatórios Gerenciais do Recrutamento e Seleção'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_RELATORIOS_GERENCIAIS_DO_RECRUTAMENTO_E_SELECAO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_RELATORIOS_GERENCIAIS_DO_RECRUTAMENTO_E_SELECAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Relatórios Gerenciais do Recrutamento e Seleção'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_RELATORIOS_GERENCIAIS_DO_RECRUTAMENTO_E_SELECAO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_RELATORIOS_GERENCIAIS_DO_RECRUTAMENTO_E_SELECAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Relatórios Gerenciais do Recrutamento e Seleção'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_RESPOSTAS_E_RESULTADOS_DA_AVALIACAO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_RESPOSTAS_E_RESULTADOS_DA_AVALIACAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Respostas e Resultados da Avaliação'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_RESPOSTAS_E_RESULTADOS_DA_AVALIACAO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_RESPOSTAS_E_RESULTADOS_DA_AVALIACAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Respostas e Resultados da Avaliação'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_RESPOSTAS_E_RESULTADOS_DA_AVALIACAO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_RESPOSTAS_E_RESULTADOS_DA_AVALIACAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Respostas e Resultados da Avaliação'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_RESPOSTAS_E_RESULTADOS_DA_AVALIACAO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_RESPOSTAS_E_RESULTADOS_DA_AVALIACAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Respostas e Resultados da Avaliação'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TIPOS_DE_APOSENTADORIAS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TIPOS_DE_APOSENTADORIAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tipos de Aposentadorias'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TIPOS_DE_APOSENTADORIAS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TIPOS_DE_APOSENTADORIAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tipos de Aposentadorias'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TIPOS_DE_APOSENTADORIAS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TIPOS_DE_APOSENTADORIAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tipos de Aposentadorias'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TIPOS_DE_APOSENTADORIAS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TIPOS_DE_APOSENTADORIAS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Tipos de Aposentadorias'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TRANSFERENCIA_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TRANSFERENCIA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Transferência'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TRANSFERENCIA_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TRANSFERENCIA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Transferência'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TRANSFERENCIA_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TRANSFERENCIA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Transferência'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_TRANSFERENCIA_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_TRANSFERENCIA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Transferência'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PENSAO_PREVIDENCIARIA_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PENSAO_PREVIDENCIARIA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Pensão Previdenciária'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PENSAO_PREVIDENCIARIA_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PENSAO_PREVIDENCIARIA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Pensão Previdenciária'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PENSAO_PREVIDENCIARIA_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PENSAO_PREVIDENCIARIA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Pensão Previdenciária'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PENSAO_PREVIDENCIARIA_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PENSAO_PREVIDENCIARIA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Pensão Previdenciária'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DECLARACAO_PARA_APOSENTADOS_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DECLARACAO_PARA_APOSENTADOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Declaração para Aposentados'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DECLARACAO_PARA_APOSENTADOS_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DECLARACAO_PARA_APOSENTADOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Declaração para Aposentados'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DECLARACAO_PARA_APOSENTADOS_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DECLARACAO_PARA_APOSENTADOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Declaração para Aposentados'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DECLARACAO_PARA_APOSENTADOS_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DECLARACAO_PARA_APOSENTADOS_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Declaração para Aposentados'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CTC_COMPENSACAO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CTC_COMPENSACAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'CTC - Compensação'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CTC_COMPENSACAO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CTC_COMPENSACAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'CTC - Compensação'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CTC_COMPENSACAO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CTC_COMPENSACAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'CTC - Compensação'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CTC_COMPENSACAO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CTC_COMPENSACAO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'CTC - Compensação'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_VERBAS_DO_PENSIONISTA_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_VERBAS_DO_PENSIONISTA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Verbas do Pensionista'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_VERBAS_DO_PENSIONISTA_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_VERBAS_DO_PENSIONISTA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Verbas do Pensionista'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_VERBAS_DO_PENSIONISTA_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_VERBAS_DO_PENSIONISTA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Verbas do Pensionista'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_VERBAS_DO_PENSIONISTA_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_VERBAS_DO_PENSIONISTA_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Verbas do Pensionista'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DTC_EX_SERVIDOR_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DTC_EX_SERVIDOR_CADASTRAR', (SELECT id FROM menu WHERE nome = 'DTC - Ex-Servidor'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DTC_EX_SERVIDOR_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DTC_EX_SERVIDOR_CADASTRAR', (SELECT id FROM menu WHERE nome = 'DTC - Ex-Servidor'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DTC_EX_SERVIDOR_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DTC_EX_SERVIDOR_CADASTRAR', (SELECT id FROM menu WHERE nome = 'DTC - Ex-Servidor'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_DTC_EX_SERVIDOR_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_DTC_EX_SERVIDOR_CADASTRAR', (SELECT id FROM menu WHERE nome = 'DTC - Ex-Servidor'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CTC_EX_SERVIDOR_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CTC_EX_SERVIDOR_CADASTRAR', (SELECT id FROM menu WHERE nome = 'CTC - Ex-Servidor'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CTC_EX_SERVIDOR_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CTC_EX_SERVIDOR_CADASTRAR', (SELECT id FROM menu WHERE nome = 'CTC - Ex-Servidor'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CTC_EX_SERVIDOR_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CTC_EX_SERVIDOR_CADASTRAR', (SELECT id FROM menu WHERE nome = 'CTC - Ex-Servidor'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CTC_EX_SERVIDOR_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CTC_EX_SERVIDOR_CADASTRAR', (SELECT id FROM menu WHERE nome = 'CTC - Ex-Servidor'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PERFIS_DE_ACESSO_CADASTRAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PERFIS_DE_ACESSO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Perfis de Acesso'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PERFIS_DE_ACESSO_ATUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PERFIS_DE_ACESSO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Perfis de Acesso'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PERFIS_DE_ACESSO_EXCLUIR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PERFIS_DE_ACESSO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Perfis de Acesso'))


IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_PERFIS_DE_ACESSO_VISUALIZAR')
INSERT INTO papel (nome, id_menu) VALUES ('ROLE_PERFIS_DE_ACESSO_CADASTRAR', (SELECT id FROM menu WHERE nome = 'Perfis de Acesso'))


END



