--Flávio Silva
--Criação de papeis.

IF EXISTS(SELECT * FROM menu WHERE nome = 'CTC - Compensação')
BEGIN
DECLARE
    @menuId AS VARCHAR(1000)

	SELECT @menuId = CAST(id AS VARCHAR(1000)) FROM menu WHERE nome = 'CTC - Compensação'
	
	IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CERTIDAO_COMPENSACAO_CADASTRAR')
		INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CERTIDAO_COMPENSACAO_CADASTRAR', @menuId)
		
	IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CERTIDAO_COMPENSACAO_ATUALIZAR')
		INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CERTIDAO_COMPENSACAO_ATUALIZAR', @menuId)
		
	IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CERTIDAO_COMPENSACAO_EXCLUIR')
		INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CERTIDAO_COMPENSACAO_EXCLUIR', @menuId)
		
	IF NOT EXISTS(SELECT * FROM papel WHERE nome = 'ROLE_CERTIDAO_COMPENSACAO_VISUALIZAR')
		INSERT INTO papel (nome, id_menu) VALUES ('ROLE_CERTIDAO_COMPENSACAO_VISUALIZAR', @menuId)
		
		
END

